version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_PASSWORD: 'frank1234'
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "7432:5432"

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    #env_file:
    #  -  ./envs/common-blockscout.env
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      BLOCK_TRANSFORMER: 'clique'
      ETHEREUM_JSONRPC_HTTP_URL: https://rpc-dev.frozenchain.io/
      DATABASE_URL: postgresql://postgres:frank1234@host.docker.internal:7432/blockscout?ssl=false
      ECTO_USE_SSL: false
    ports:
      - "127.0.0.1:4000:4000"